#!/usr/bin/env python3
"""
Import a Claude.ai conversation export (JSON) into the journal log format.

Produces entries/YYYY/MM/YYYY-MM-DD.log.md files matching the format
generated by export-log.py — one file per day, grouped by local time.

Usage:
    python3 scripts/import-claude-ai.py                        # default: import/import.json
    python3 scripts/import-claude-ai.py path/to/export.json   # specific file
"""

import json
import sys
from datetime import datetime, timedelta
from pathlib import Path
from collections import defaultdict


def journal_date(dt):
    """Return the journal date for a datetime — days run 05:00 to 05:00."""
    if dt.hour < 5:
        return (dt - timedelta(days=1)).date()
    return dt.date()

JOURNAL_DIR = Path(__file__).parent.parent.resolve()
DEFAULT_IMPORT = JOURNAL_DIR / 'import' / 'import.json'


def user_name():
    """Read the user's name from profile/stable.md, fallback to 'User'."""
    stable = JOURNAL_DIR / 'profile' / 'stable.md'
    if stable.exists():
        for line in stable.read_text(encoding='utf-8').splitlines():
            line = line.strip()
            if line.startswith('# '):
                name = line[2:].strip()
                if name:
                    return name
    return 'User'


def parse_timestamp(ts_str):
    """Parse ISO 8601 timestamp and convert to local time."""
    dt = datetime.fromisoformat(ts_str.replace('Z', '+00:00'))
    return dt.astimezone()


def format_time(dt):
    return dt.strftime('%H:%M')


def extract_text(content):
    """Concatenate all text blocks from a message's content array."""
    parts = [
        block.get('text', '').strip()
        for block in content
        if block.get('type') == 'text' and block.get('text', '').strip()
    ]
    return '\n\n'.join(parts)


def main():
    import_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_IMPORT

    if not import_path.exists():
        print(f"Error: file not found: {import_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Loading {import_path} ...")
    with open(import_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    messages = data.get('chat_messages', [])
    print(f"Found {len(messages)} messages")

    # Group by local date
    by_date = defaultdict(list)

    for msg in messages:
        sender = msg.get('sender', '')
        if sender == 'human':
            role = user_name()
        elif sender == 'assistant':
            role = 'Claude'
        else:
            continue

        content = msg.get('content', [])
        text = extract_text(content)
        if not text:
            continue

        # Use the start_timestamp of first content block, fall back to created_at
        ts_str = None
        if content:
            ts_str = content[0].get('start_timestamp')
        if not ts_str:
            ts_str = msg.get('created_at')
        if not ts_str:
            continue

        try:
            dt = parse_timestamp(ts_str)
        except (ValueError, KeyError):
            continue

        by_date[journal_date(dt)].append({
            'dt': dt,
            'role': role,
            'text': text,
        })

    if not by_date:
        print("No messages extracted.", file=sys.stderr)
        sys.exit(1)

    print(f"Spanning {len(by_date)} days: {min(by_date)} → {max(by_date)}")

    written = []
    for entry_date, entries in sorted(by_date.items()):
        entries.sort(key=lambda x: x['dt'])

        date_str = entry_date.strftime('%Y-%m-%d')
        year = entry_date.strftime('%Y')
        month = entry_date.strftime('%m')

        output_dir = JOURNAL_DIR / 'entries' / year / month
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f'{date_str}.log.md'

        if output_path.exists():
            print(f"  SKIP (exists): {output_path.relative_to(JOURNAL_DIR)}")
            continue

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(f'# {date_str}\n\n')
            for entry in entries:
                f.write(f"## {format_time(entry['dt'])} — {entry['role']}\n")
                f.write(entry['text'])
                f.write('\n\n')

        written.append(output_path)
        print(f"  {output_path.relative_to(JOURNAL_DIR)}  ({len(entries)} messages)")

    print(f"\nDone. Wrote {len(written)} file(s).")


if __name__ == '__main__':
    main()
